create table EMPLOYEE (
  employeeId bigint generated by default as identity (start with 1),
  name varchar(255),
  address varchar(255),
  email varchar(255),
  primary key (employeeId)
);

create table PAYMENT_TYPE (
  employeeId bigint not null,
  primary key (employeeId)
);

create table HOURLY (
  employeeId bigint not null,
  hourRate integer, primary key (employeeId)
);

create table MONTHLY (
  employeeId bigint not null,
  salary integer,
  primary key (employeeId)
);

create table COMMISSION (
  employeeId bigint not null,
  commissionRate integer,
  primary key (employeeId)
);

create table SALES_RECEIPT (
  id bigint generated by default as identity (start with 1),
  date timestamp,
  amount integer,
  employeeId bigint not null,
  primary key (id)
);

create table TIME_CARD (
  id bigint generated by default as identity (start with 1),
  date timestamp,
  hours integer,
  employeeId bigint not null,
  primary key (id)
);

alter table PAYMENT_TYPE add constraint FK_PAYMENT_TYPE_EMPLOYEE foreign key (employeeId) references EMPLOYEE;

alter table COMMISSION add constraint FK_COMISSION_PAYMENT_TYPE foreign key (employeeId) references PAYMENT_TYPE;

alter table HOURLY add constraint FK_HOURLY_PAYMENT_TYPE foreign key (employeeId) references PAYMENT_TYPE;

alter table MONTHLY add constraint FK_MONTHLY_PAYMENT_TYPE foreign key (employeeId) references PAYMENT_TYPE;

alter table SALES_RECEIPT add constraint FK_SALES_RECEIPT_COMMISION foreign key (employeeId) references COMMISSION;

alter table TIME_CARD add constraint FK_TIME_CARD_COMMISION foreign key (employeeId) references HOURLY;
